language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - functions/node_modules
script:
  - npm test
after_success:
  - npm run build
  - firebase use default --token $FIREBASE_TOKEN
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master