language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - functions/node_modules
before_install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
script:
  - npm test
after_success:
  - CI=false npm run build
  - firebase use default --token $FIREBASE_TOKEN
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN --debug
branches:
  only:
    - master