language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - functions/node_modules
before_install:
  - rm -rf node_modules
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
script:
  - npm test
  - npm run build
deploy:
  provider: firebase
  skip_cleaup: true
  token: 
    secure: $FIREBASE_TOKEN
branches:
  only:
    - master